### ISSUE TITLE
yoga duet iml 2020 的安装macos的bois相关设置

### ISSUE THREAD

**Issue by aTan20170106** [xudingjun3131/yoga-duet-2020-mac#1]
你好！请问，能补充一下yoga duet iml 2020的bois中的相关设置吗？
因为我F2进去和常规黑苹果设置的BOIS不一样，所以不清楚该如何设置。

**Comment by xudingjun3131** [comment]
看上去只要关掉secure boot 


目前已经升级到14版本，不过触屏和键盘不兼容。

**Comment by aTan20170106** [comment]
非常感谢回答，如果只要关掉secure boot操作就简单多了。因为之前我安装macos都需要关闭掉TPM，vt-d,vt-x还有其它的选项的。升级到14版本不兼容。13版本可以兼容那已经不错的啦。

**Comment by xudingjun3131** [comment]
你可以试试，祝你好运
