### ISSUE TITLE
驱动声卡

### ISSUE THREAD

**Issue by aTan20170106** [xudingjun3131/yoga-duet-2020-mac#2]
你好，
macos版本： 12.0
1、(主要)  我使用了万能声卡voodoohda，并且放到了/L/E里面。使用了hackintool重建缓存。但并不起作用，能不能请教一下具体的步骤
2、使用了applealc 1.7.4版本，使用了id=21,耳机可以听到声音，但内置外放不行，这个找了一下资料。在黑果小兵中的
https://blog.daliansky.net/Use-AppleALC-sound-card-to-drive-the-correct-posture-of-AppleHDA.html 发“声卡驱动了,音量调节的图标也显示正常,就是不发声怎么办”那里使用hda-tool或者hda-ver命令去修复。目前没读明白里面的内容，目前研究一下定制。在linux发现内置麦在linux在cd 的情况下没有的。

**Comment by xudingjun3131** [comment]
这个问题我也出现了，用万能声卡驱动一个就可以了， 不过也需要手工切换下才行，问题不大。具体怎么操作的我也忘记了，蛮久了。

**Comment by aTan20170106** [comment]
尝试过很多办法无法在12.0上让外放出声，已经用万能声卡和并且nodesToPatch节点与写上去了。并且imix的电平修改为100耳机的mic录制的声音还不错。
